<centro>
     <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="300" alt="cognitiveclass.ai logo" >
</center>

# Laboratório prático: exemplos de API
## Exemplos de usuários aleatórios e API Fruityvice


Tempo estimado necessário: **30** minutos

## Objetivos

Depois de concluir este laboratório, você será capaz de:

* Carregue e use a API RandomUser, usando a biblioteca Python `RandomUser()`
* Carregar e usar a API Fruityvice, usando a biblioteca Python `requests`
* Carregar e usar Open-Joke-API, usando a biblioteca Python `requests`

O objetivo deste notebook é fornecer mais exemplos de como usar APIs simples. Como você já aprendeu em vídeos e notebooks anteriores, API significa Application Programming Interface e é um intermediário de software que permite que dois aplicativos se comuniquem.

As vantagens de usar APIs:
  * **Automação**. É necessário menos esforço humano e os fluxos de trabalho podem ser facilmente atualizados para se tornarem mais rápidos e eficientes.
      produtivo.
  * **Eficiência**. Permite usar os recursos de uma das APIs já desenvolvidas do que tentar
      implementar de forma independente algumas funcionalidades do zero.
 
A desvantagem de usar APIs:
  *   **Segurança**. Se a API estiver mal integrada, significa que estará vulnerável a ataques, resultando em violações ou perdas de dados com implicações financeiras ou de reputação.

Um dos aplicativos que usaremos neste notebook é o Random User Generator. RandomUser é uma API gratuita e de código aberto que fornece aos desenvolvedores usuários gerados aleatoriamente para serem usados como espaços reservados para fins de teste. Isso torna a ferramenta semelhante ao Lorem Ipsum, mas é um espaço reservado para pessoas em vez de texto. A API pode retornar vários resultados, bem como especificar detalhes do usuário gerados, como sexo, e-mail, imagem, nome de usuário, endereço, título, nome e sobrenome e muito mais. Mais informações sobre [RandomUser](https://randomuser.me/documentation#intro) podem ser encontradas aqui.

Outro exemplo de API simples que usaremos neste notebook é o aplicativo Fruityvice. O serviço web Fruityvice API que fornece dados para todos os tipos de frutas! Você pode usar o Fruityvice para descobrir informações interessantes sobre frutas e se educar. O serviço da web é totalmente gratuito para usar e contribuir.

## Exemplo 1: API RandomUser
Abaixo estão os parâmetros Get Methods que podemos gerar. Para obter mais informações sobre os parâmetros, visite esta página de [documentação](https://randomuser.me/documentation).

## **Metódos Get**

- get_cell()
- get_city()
- get_dob()
- get_email()
- get_first_name()
- get_full_name()
- get_gender()
- get_id()
- get_id_number()
- get_id_type()
- get_info()
- get_last_name()
- get_login_md5()
- get_login_salt()
- get_login_sha1()
- get_login_sha256()
- get_nat()
- get_password()
- get_phone()
- get_picture()
- get_postcode()
- get_registered()
- get_state()
- get_street()
- get_username()
- get_zipcode()

Para começar a usar a API você pode instalar a biblioteca `randomuser` executando o comando `pip install`.

Em seguida, carregaremos as bibliotecas necessárias.

In [1]:
from randomuser import RandomUser
import pandas as pd

Primeiro, criaremos um objeto de usuário aleatório, r.

In [2]:
r = RandomUser()

Então, usando a função `generate_users()`, obtemos uma lista de 10 usuários aleatórios.

In [3]:
some_list = r.generate_users(10)

In [4]:
some_list

[<randomuser.RandomUser at 0x12283b410>,
 <randomuser.RandomUser at 0x12283b450>,
 <randomuser.RandomUser at 0x12283b490>,
 <randomuser.RandomUser at 0x12283b4d0>,
 <randomuser.RandomUser at 0x12283b510>,
 <randomuser.RandomUser at 0x12283b590>,
 <randomuser.RandomUser at 0x12283b5d0>,
 <randomuser.RandomUser at 0x12283b610>,
 <randomuser.RandomUser at 0x12283b650>,
 <randomuser.RandomUser at 0x12283b550>]

As funções **"Metódos Get"** mencionadas no início deste notebook podem gerar os parâmetros necessários para construir um conjunto de dados. Por exemplo, para obter o nome completo, chamamos a função `get_full_name()`.

In [5]:
name = r.get_full_name()

In [6]:
name

'Sibilla Stehle'

Digamos que precisamos apenas de 10 usuários com nomes completos e endereços de e-mail. Podemos escrever um "for-loop" para imprimir esses 10 usuários.

In [7]:
for user in some_list:
    print (user.get_full_name()," ",user.get_email())

محمدعلی یاسمی   mhmdaaly.ysmy@example.com
Isaac Lefevre   isaac.lefevre@example.com
Anton Andersen   anton.andersen@example.com
Flenn Wells   flenn.wells@example.com
Jeppe Rasmussen   jeppe.rasmussen@example.com
Amel Roerdink   amel.roerdink@example.com
Valerie Fuller   valerie.fuller@example.com
August Mortensen   august.mortensen@example.com
پرهام یاسمی   prhm.ysmy@example.com
Carolyn Schmidt   carolyn.schmidt@example.com

<hr>

## Exercício 1
Neste exercício, gere fotos de 10 usuários aleatórios.

In [8]:
for user in some_list:
    print (user.get_picture())

https://randomuser.me/api/portraits/men/90.jpg
https://randomuser.me/api/portraits/men/17.jpg
https://randomuser.me/api/portraits/men/7.jpg
https://randomuser.me/api/portraits/men/62.jpg
https://randomuser.me/api/portraits/men/69.jpg
https://randomuser.me/api/portraits/men/21.jpg
https://randomuser.me/api/portraits/women/61.jpg
https://randomuser.me/api/portraits/men/15.jpg
https://randomuser.me/api/portraits/men/81.jpg
https://randomuser.me/api/portraits/women/95.jpg

Para gerar uma tabela com informações sobre os usuários, podemos escrever uma função contendo todos os parâmetros desejáveis. Por exemplo, nome, sexo, cidade, etc. Os parâmetros dependerão dos requisitos do teste a ser realizado. Chamamos os Métodos Get, listados no início deste caderno. Em seguida, retornamos o dataframe do pandas com os usuários.

In [9]:
def get_users():
    users =[]
     
    for user in RandomUser.generate_users(10):
        users.append({"Name":user.get_full_name(),"Gender":user.get_gender(),"City":user.get_city(),"State":user.get_state(),"Email":user.get_email(), "DOB":user.get_dob(),"Picture":user.get_picture()})
      
    return pd.DataFrame(users)

In [10]:
get_users()

,Name,Gender,City,State,Email,DOB,Picture
0,Olivia Jørgensen,female,Stoevring,Midtjylland,olivia.jorgensen@example.com,1945-09-02T07:00:47.881Z,https://randomuser.me/api/portraits/women/23.jpg
1,Hanna Newman,female,Laytown-Bettystown-Mornington,Monaghan,hanna.newman@example.com,1986-11-18T09:15:38.331Z,https://randomuser.me/api/portraits/women/52.jpg
2,Camille Brown,female,Sutton,Yukon,camille.brown@example.com,1970-02-14T02:31:14.458Z,https://randomuser.me/api/portraits/women/43.jpg
3,Pauline Theuws,female,Terhole,Drenthe,pauline.theuws@example.com,1951-03-26T02:08:34.698Z,https://randomuser.me/api/portraits/women/34.jpg
4,Andréa Moreau,female,Courbevoie,Allier,andrea.moreau@example.com,1993-01-22T23:23:24.041Z,https://randomuser.me/api/portraits/women/60.jpg
5,Victor Christiansen,male,Ishoej,Midtjylland,victor.christiansen@example.com,1982-12-14T17:54:34.873Z,https://randomuser.me/api/portraits/men/69.jpg
6,Irma Thomas,female,Oberentfelden,Schwyz,irma.thomas@example.com,1978-07-02T04:35:18.558Z,https://randomuser.me/api/portraits/women/70.jpg
7,Eloane Fernandez,female,Versailles,Hautes-Alpes,eloane.fernandez@example.com,1993-09-04T19:53:06.201Z,https://randomuser.me/api/portraits/women/37.jpg
8,Aaron Harper,male,Buncrana,Dublin City,aaron.harper@example.com,1968-06-15T07:05:21.569Z,https://randomuser.me/api/portraits/men/7.jpg
9,Edgar Roche,male,Toulouse,Charente,edgar.roche@example.com,1951-07-20T00:06:23.563Z,https://randomuser.me/api/portraits/men/32.jpg

In [11]:
df1 = pd.DataFrame(get_users())

In [13]:
df1

,Name,Gender,City,State,Email,DOB,Picture
0,Josette Rodriguez,female,Birrhard,Nidwalden,josette.rodriguez@example.com,1955-03-03T18:59:00.052Z,https://randomuser.me/api/portraits/women/2.jpg
1,حامد محمدخان,male,زاهدان,خوزستان,hmd.mhmdkhn@example.com,1994-09-04T03:01:03.394Z,https://randomuser.me/api/portraits/men/20.jpg
2,Arnaud Barnaby,male,Keswick,Ontario,arnaud.barnaby@example.com,1946-02-09T13:37:59.890Z,https://randomuser.me/api/portraits/men/89.jpg
3,Herbert Foster,male,Monaghan,Kilkenny,herbert.foster@example.com,1974-10-25T16:34:47.910Z,https://randomuser.me/api/portraits/men/81.jpg
4,Wolf-Dietrich Kreft,male,Leonberg,Schleswig-Holstein,wolf-dietrich.kreft@example.com,1994-03-02T18:06:11.078Z,https://randomuser.me/api/portraits/men/71.jpg
5,Jackson Walker,male,Gisborne,Marlborough,jackson.walker@example.com,1976-09-10T16:10:21.977Z,https://randomuser.me/api/portraits/men/88.jpg
6,Pippa Patel,female,Nelson,Auckland,pippa.patel@example.com,1998-04-24T15:06:31.226Z,https://randomuser.me/api/portraits/women/92.jpg
7,Alfons Güttler,male,Breisach am Rhein,Hamburg,alfons.guttler@example.com,1972-04-27T22:43:17.740Z,https://randomuser.me/api/portraits/men/20.jpg
8,Selena Magnus,female,Setermoen,Rogaland,selena.magnus@example.com,1979-04-30T06:37:44.394Z,https://randomuser.me/api/portraits/women/38.jpg
9,Marian Rivera,female,Salem,New York,marian.rivera@example.com,1963-04-28T09:52:23.130Z,https://randomuser.me/api/portraits/women/60.jpg

Agora temos um dataframe do pandas que pode ser usado para qualquer finalidade de teste que o testador possa ter.

<hr>

## Exemplo 2: API Fruityvice

Outra forma mais comum de usar APIs é por meio da biblioteca `requests`. O próximo laboratório, Solicitações e HTTP, conterá mais informações sobre solicitações.

Começaremos importando todas as bibliotecas necessárias.

In [14]:
import requests
import json

Obteremos os dados da API [fruityvice](https://www.fruityvice.com) usando a função `requests.get("url")`. Os dados estão em formato json.

In [15]:
data = requests.get("https://fruityvice.com/api/fruit/all")

Recuperaremos os resultados usando a função `json.loads()`.

In [16]:
results = json.loads(data.text)

Converteremos seus dados json em dataframe do pandas

In [18]:
pd.DataFrame(results)

,name,id,family,order,genus,nutritions
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,"{'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'c..."
1,Strawberry,3,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
2,Banana,1,Musaceae,Zingiberales,Musa,"{'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'c..."
3,Tomato,5,Solanaceae,Solanales,Solanum,"{'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'ca..."
4,Pear,4,Rosaceae,Rosales,Pyrus,"{'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'c..."
5,Durian,60,Malvaceae,Malvales,Durio,"{'calories': 147, 'fat': 5.3, 'sugar': 6.75, '..."
6,Blackberry,64,Rosaceae,Rosales,Rubus,"{'calories': 40, 'fat': 0.4, 'sugar': 4.5, 'ca..."
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,"{'calories': 50, 'fat': 0.34, 'sugar': 5.74, '..."
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,"{'calories': 61, 'fat': 0.5, 'sugar': 9.0, 'ca..."
9,Lychee,67,Sapindaceae,Sapindales,Litchi,"{'calories': 66, 'fat': 0.44, 'sugar': 15.0, '..."
10,Pineapple,10,Bromeliaceae,Poales,Ananas,"{'calories': 50, 'fat': 0.12, 'sugar': 9.85, '..."
11,Fig,68,Moraceae,Rosales,Ficus,"{'calories': 74, 'fat': 0.3, 'sugar': 16.0, 'c..."
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,"{'calories': 44, 'fat': 0.6, 'sugar': 0.0, 'ca..."
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,"{'calories': 97, 'fat': 0.7, 'sugar': 11.2, 'c..."
14,Plum,71,Rosaceae,Rosales,Prunus,"{'calories': 46, 'fat': 0.28, 'sugar': 9.92, '..."
15,Orange,2,Rutaceae,Sapindales,Citrus,"{'calories': 43, 'fat': 0.2, 'sugar': 8.2, 'ca..."
16,GreenApple,72,Rosaceae,Rosales,Malus,"{'calories': 21, 'fat': 0.1, 'sugar': 6.4, 'ca..."
17,Raspberry,23,Rosaceae,Rosales,Rubus,"{'calories': 53, 'fat': 0.7, 'sugar': 4.4, 'ca..."
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,"{'calories': 30, 'fat': 0.2, 'sugar': 6.0, 'ca..."
19,Lemon,26,Rutaceae,Sapindales,Citrus,"{'calories': 29, 'fat': 0.3, 'sugar': 2.5, 'ca..."
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,"{'calories': 60, 'fat': 0.38, 'sugar': 13.7, '..."
21,Blueberry,33,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
22,Apple,6,Rosaceae,Rosales,Malus,"{'calories': 52, 'fat': 0.4, 'sugar': 10.3, 'c..."
23,Guava,37,Myrtaceae,Myrtales,Psidium,"{'calories': 68, 'fat': 1.0, 'sugar': 9.0, 'ca..."
24,Apricot,35,Rosaceae,Rosales,Prunus,"{'calories': 15, 'fat': 0.1, 'sugar': 3.2, 'ca..."
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,"{'calories': 34, 'fat': 0.0, 'sugar': 8.0, 'ca..."
26,Tangerine,77,Rutaceae,Sapindales,Citrus,"{'calories': 45, 'fat': 0.4, 'sugar': 9.1, 'ca..."
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,"{'calories': 36, 'fat': 0.4, 'sugar': 3.0, 'ca..."
28,Lime,44,Rutaceae,Sapindales,Citrus,"{'calories': 25, 'fat': 0.1, 'sugar': 1.7, 'ca..."
29,Pomegranate,79,Lythraceae,Myrtales,Punica,"{'calories': 83, 'fat': 1.2, 'sugar': 13.7, 'c..."
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,"{'calories': 60, 'fat': 1.5, 'sugar': 8.0, 'ca..."
31,Grape,81,Vitaceae,Vitales,Vitis,"{'calories': 69, 'fat': 0.16, 'sugar': 16.0, '..."
32,Morus,82,Moraceae,Rosales,Morus,"{'calories': 43, 'fat': 0.39, 'sugar': 8.1, 'c..."
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,"{'calories': 44, 'fat': 0.4, 'sugar': 3.0, 'ca..."
34,Avocado,84,Lauraceae,Laurales,Persea,"{'calories': 160, 'fat': 14.66, 'sugar': 0.66,..."
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,"{'calories': 61, 'fat': 0.5, 'sugar': 8.9, 'ca..."
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,"{'calories': 46, 'fat': 0.1, 'sugar': 4.0, 'ca..."
37,Cherry,9,Rosaceae,Rosales,Prunus,"{'calories': 50, 'fat': 0.3, 'sugar': 8.0, 'ca..."
38,Peach,86,Rosaceae,Rosales,Prunus,"{'calories': 39, 'fat': 0.25, 'sugar': 8.4, 'c..."
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,"{'calories': 95, 'fat': 0.0, 'sugar': 19.1, 'c..."
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,"{'calories': 44, 'fat': 1.26, 'sugar': 0.5, 'c..."
41,Hazelnut,96,Betulaceae,Fagales,Corylus,"{'calories': 628, 'fat': 61.0, 'sugar': 4.3, '..."
42,Pomelo,98,Rutaceae,Sapindales,Citrus,"{'calories': 37, 'fat': 0.0, 'sugar': 8.5, 'ca..."
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,"{'calories': 73, 'fat': 0.58, 'sugar': 16.11, ..."
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,"{'calories': 25, 'fat': 0.3, 'sugar': 3.3, 'ca..."
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,"{'calories': 70, 'fat': 0.2, 'sugar': 13.0, 'c..."
46,Papaya,42,Caricaceae,Brassicales,Carica,"{'calories': 39, 'fat': 0.3, 'sugar': 4.4, 'ca..."
47,Annona,103,Annonaceae,Rosales,Annonas,"{'calories': 92, 'fat': 0.29, 'sugar': 3.4, 'c..."
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,"{'calories': 47, 'fat': 0.3, 'sugar': 8.1, 'ca..."

The result is in a nested json format. The 'nutrition' column contains multiple subcolumns, so the data needs to be 'flattened' or normalized.

In [20]:
df2 = pd.json_normalize(results)

In [21]:
df2

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.00,18.00,18.00,0.00
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.80
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.20,17.20,22.00,1.00
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.20,2.60,3.90,0.90
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.10,10.00,15.00,0.40
5,Durian,60,Malvaceae,Malvales,Durio,147,5.30,6.75,27.10,1.50
6,Blackberry,64,Rosaceae,Rosales,Rubus,40,0.40,4.50,9.00,1.30
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,50,0.34,5.74,11.30,0.75
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,61,0.50,9.00,15.00,1.10
9,Lychee,67,Sapindaceae,Sapindales,Litchi,66,0.44,15.00,17.00,0.80
10,Pineapple,10,Bromeliaceae,Poales,Ananas,50,0.12,9.85,13.12,0.54
11,Fig,68,Moraceae,Rosales,Ficus,74,0.30,16.00,19.00,0.80
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,44,0.60,0.00,10.00,0.90
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,97,0.70,11.20,22.40,2.20
14,Plum,71,Rosaceae,Rosales,Prunus,46,0.28,9.92,11.40,0.70
15,Orange,2,Rutaceae,Sapindales,Citrus,43,0.20,8.20,8.30,1.00
16,GreenApple,72,Rosaceae,Rosales,Malus,21,0.10,6.40,3.10,0.40
17,Raspberry,23,Rosaceae,Rosales,Rubus,53,0.70,4.40,12.00,1.20
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,30,0.20,6.00,8.00,0.60
19,Lemon,26,Rutaceae,Sapindales,Citrus,29,0.30,2.50,9.00,1.10
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,60,0.38,13.70,15.00,0.82
21,Blueberry,33,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.00
22,Apple,6,Rosaceae,Rosales,Malus,52,0.40,10.30,11.40,0.30
23,Guava,37,Myrtaceae,Myrtales,Psidium,68,1.00,9.00,14.00,2.60
24,Apricot,35,Rosaceae,Rosales,Prunus,15,0.10,3.20,3.90,0.50
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,34,0.00,8.00,8.00,0.00
26,Tangerine,77,Rutaceae,Sapindales,Citrus,45,0.40,9.10,8.30,0.00
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,36,0.40,3.00,7.00,1.00
28,Lime,44,Rutaceae,Sapindales,Citrus,25,0.10,1.70,8.40,0.30
29,Pomegranate,79,Lythraceae,Myrtales,Punica,83,1.20,13.70,18.70,1.70
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,60,1.50,8.00,9.00,9.00
31,Grape,81,Vitaceae,Vitales,Vitis,69,0.16,16.00,18.10,0.72
32,Morus,82,Moraceae,Rosales,Morus,43,0.39,8.10,9.80,1.44
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,44,0.40,3.00,8.00,0.60
34,Avocado,84,Lauraceae,Laurales,Persea,160,14.66,0.66,8.53,2.00
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,61,0.50,8.90,14.60,1.14
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,46,0.10,4.00,12.20,0.40
37,Cherry,9,Rosaceae,Rosales,Prunus,50,0.30,8.00,12.00,1.00
38,Peach,86,Rosaceae,Rosales,Prunus,39,0.25,8.40,9.50,0.90
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,95,0.00,19.10,23.20,1.72
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,44,1.26,0.50,7.56,1.78
41,Hazelnut,96,Betulaceae,Fagales,Corylus,628,61.00,4.30,17.00,15.00
42,Pomelo,98,Rutaceae,Sapindales,Citrus,37,0.00,8.50,9.67,0.82
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,73,0.58,16.11,17.91,0.41
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,25,0.30,3.30,4.60,1.10
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,70,0.20,13.00,19.00,0.60
46,Papaya,42,Caricaceae,Brassicales,Carica,39,0.30,4.40,5.80,0.50
47,Annona,103,Annonaceae,Rosales,Annonas,92,0.29,3.40,19.10,1.50
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,47,0.30,8.10,9.60,1.20

Vamos ver se conseguimos extrair algumas informações deste dataframe. Talvez precisemos conhecer a família e o gênero de uma cereja.

In [22]:
cherry = df2.loc[df2["name"] == 'Cherry']
(cherry.iloc[0]['family']) , (banana.iloc[0]['genus'])

('Rosaceae', 'Prunus')

<hr>

## Exercício 2
Neste exercício, descubra quantas calorias contém uma banana.

In [25]:
cal_banana = df2.loc[df2["name"] == 'Banana']
cal_banana.iloc[0]['nutritions.calories']

96

<hr>

## Exercício 3

Esta [página](https://mixedanalytics.com/blog/list-actually-free-open-no-auth-needed-apis/) contém uma lista de APIs públicas gratuitas para você praticar. Vamos lidar com o seguinte exemplo.

#### API oficial de piadas
Esta API retorna piadas aleatórias de um banco de dados. O URL a seguir pode ser usado para recuperar 10 piadas aleatórias.

https://official-joke-api.appspot.com/jokes/ten

1. Usando a função `requests.get("url")`, carregue os dados do URL.

In [28]:
url= 'https://official-joke-api.appspot.com/jokes/ten'
data2=requests.get(url)

In [29]:
url

'https://official-joke-api.appspot.com/jokes/ten'

2. Recupere os resultados usando a função `json.loads()`.

In [30]:
results2 = json.loads(data2.text)

In [31]:
results2

[{'type': 'general',
  'setup': 'What did the pirate say on his 80th birthday?',
  'punchline': 'Aye Matey!',
  'id': 183},
 {'type': 'general',
  'setup': "Why didn't the skeleton go for prom?",
  'punchline': 'Because it had nobody.',
  'id': 404},
 {'type': 'general',
  'setup': 'What do you call a fashionable lawn statue with an excellent sense of rhythmn?',
  'punchline': 'A metro-gnome',
  'id': 207},
 {'type': 'general',
  'setup': 'What did the duck say when he bought lipstick?',
  'punchline': 'Put it on my bill',
  'id': 30},
 {'type': 'general',
  'setup': 'How do you get a baby alien to sleep?',
  'punchline': ' You rocket.',
  'id': 125},
 {'type': 'general',
  'setup': 'What did the mountain climber name his son?',
  'punchline': 'Cliff.',
  'id': 179},
 {'type': 'general',
  'setup': 'How do you make a tissue dance?',
  'punchline': 'You put a little boogie on it.',
  'id': 2},
 {'type': 'general',
  'setup': 'Want to hear my pizza joke?',
  'punchline': "Never mind, it's too cheesy.",
  'id': 154},
 {'type': 'general',
  'setup': 'If you see a robbery at an Apple Store...',
  'punchline': 'Does that make you an iWitness?',
  'id': 42},
 {'type': 'general',
  'setup': 'Have you heard of the band 1023MB?',
  'punchline': "They haven't got a gig yet.",
  'id': 111}]

Converta dados json em quadro de dados do pandas. Elimine as colunas de tipo e id

In [32]:
df3 = pd.DataFrame(results2)
df3.drop(columns=["type","id"],inplace=True)
df3

,setup,punchline
0,What did the pirate say on his 80th birthday?,Aye Matey!
1,Why didn't the skeleton go for prom?,Because it had nobody.
2,What do you call a fashionable lawn statue wit...,A metro-gnome
3,What did the duck say when he bought lipstick?,Put it on my bill
4,How do you get a baby alien to sleep?,You rocket.
5,What did the mountain climber name his son?,Cliff.
6,How do you make a tissue dance?,You put a little boogie on it.
7,Want to hear my pizza joke?,"Never mind, it's too cheesy."
8,If you see a robbery at an Apple Store...,Does that make you an iWitness?
9,Have you heard of the band 1023MB?,They haven't got a gig yet.